# Generated by Django 4.1.7 on 2023-03-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='core.question')),
            ],
        ),
    ]
