# Generated by Django 4.1.7 on 2023-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
