# Generated by Django 4.1.7 on 2023-04-19 09:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_explanation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
